name: Bug report
description: Create a report to help us improve
title: '[Bug] '
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the Bug
      description: >-
        Provide a clear and concise description of what the bug is, and what
        should have happened.
      placeholder: Required
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior (Err on over-descriptive).
      placeholder: Required
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: >-
        If applicable, include screenshots, OS/Browser/Build version, or any
        other relevant information.
      placeholder: Required
    validations:
      required: true
