name: Suggestion
description: Suggest an idea for this project
title: '[Suggestion] '
labels:
  - suggestion
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: Provide a clear and concise description of the suggestion.
      placeholder: Required
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: >-
        Provide a clear and concise explanation for what changes would need to
        take place in order for the suggestion to be possible.
      placeholder: Required
    validations:
      required: true
